apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leases-playground-rolebinding
subjects:
  - kind: ServiceAccount
    name: leases-playground-sa
roleRef:
  kind: Role
  name: leases-playground-role
  apiGroup: rbac.authorization.k8s.io

