name: Build
on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build singleton
        run: scala-cli --power package --docker singleton.sc --docker-image-repository ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/singleton

      - name: Push singleton
        run: docker push ${{env.REGISTRY}}/${{ env.REPOSITORY }}/singleton
